name: Deploy code to AWS S3 bucket

on:
  push:
    branches:
      - main  # added a space

jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest  # fixed indentation and key

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # using latest version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-3

      - name: Deploy to S3
        run: aws s3 sync . s3://rohit-zoro-luffy --delete
